### PR TITLE
- Fixed bug in Fasta parser, where if the sequence wasn't accessed wh…

### PR DESCRIPTION
**Pull request by lairdm**
…en cycling through records the pointer didn't advance correctly (one too many records was reported existing)

- Added support for Fasta embedded in GFF3 files via an embedded Fasta parser when the ##FASTA tag is reached
- Made the return from read_block() explicit

### CODE REVIEW

**Comment by lairdm** [comment]
Hmm, back to the drawing board on that merge...

**Comment by ens-ap5** [comment]
Shall I hold off, then?

Anne

**Comment by lairdm** [comment]
Yes please, I didn't touch the variation section, but let me poke around to
see if I can find why those tests failed.

**Comment by nerdstrike** [comment]
They've been failing previously, I doubt it's @lairdm 's fault.

**Comment by lairdm** [comment]
Ahh, hadn't dug that far back yet, was just looking. Alright, proceed then
if you're happy with the changes :)

**Comment by ens-ap5** [comment]
OK, I’ll have a look.

Anne

**Comment by ens-ap5** [comment]
Is there a reason that the new methods in the GFF parser have camelcase names? If not, could you rename them? We've moved towards using lowercase_with_underscores throughout the parser code (the perils of having contributors from different teams and no pre-agreed conventions!).

**Comment by lairdm** [comment]
Yes, these 4 subroutines are direct mappings to the equivalent routines in the Fasta parser and pass straight through in order to access Fasta embedded in a GFF3.  I wanted to keep the calls identical to the Fasta parser calls to remove any confusion and allow better code reuse, reading the sequence from a "Fasta" (embedded or not) is always GetSequence(). Now why those are camel case, that's a question for whoever wrote the Fasta parser :)

**Comment by ens-ap5** [comment]
OK, I’ll merge it as-is, and we can rationalise the method names later.

Cheers

Anne

**Pull request merged**
