### PR TITLE
Bugfix/filechameleon gtf error

### PR DESCRIPTION
**Pull request by s-mm**
Fix for [ENSCORESW-3150](https://www.ebi.ac.uk/panda/jira/browse/ENSCORESW-3150). Code modified to handle multidimensional hash. This fix should be combined with changes in 
`format-transcriber/lib/Bio/FormatTranscriber.pm`.

### CODE REVIEW

**Comment by ens-bwalts** [comment]
I'm still getting the 
```
Can't locate object method "combine_fields" via package "Bio::EnsEMBL::IO::Object::GTF"
```
error when I try to run format-transcriber/bin/format-transcriber.pl using this branch and the corresponding branch in format-transcriber

**Comment by s-mm** [comment]
@ens-bwalts  The error has been fixed. Please try again with the latest commit.

**Comment by s-mm** [comment]
I will merge this branch after web-team confirms this issue has been resolved.

**Comment by s-mm** [comment]
Tested by Ridwan in web team. Comments here- https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5060

**Pull request merged**
