### PR TITLE
Existing TABIX functionality via Bio::DB::HTS

### PR DESCRIPTION
**Pull request by rishidev**
This upgrades ensembl-io to use tabix functionality from Bio::DB::HTS (https://github.com/Ensembl/Bio-HTS) and HTSlib to improve performance rather than calling the command line executable. It passes the tabix related t tests but I think these fail for other reasons.

### CODE REVIEW

**Comment by ens-ap5** [comment]
Is there a reason to add BioPerl 1.2.3 to travis? I thought we'd completely abandoned that version over a year ago, when all the webcode was finally made compatible with 1.6.x

**Comment by rishidev** [comment]
The BioPerl 1.2.3 is the existing version being used in the ensembl-io travis tests, but I will upgrade this to a 1.6 version.

**Comment by andrewyatz** [comment]
Think I just tried to get a bioperl in there. Plus the original change was mine back in August 2015 so were we 1.6 compliant then?

**Comment by rishidev** [comment]
Having had a look at a few repos they're all on 1.2.3 for Travis tests bar the ensembl core repo which was only set to 1.6.1 at the end of January.

**Comment by ens-ap5** [comment]
OK. TBH I haven’t looked into travis, as we don’t use it with the web code.

Anne

**Comment by muffato** [comment]
compara should be on the 1.6.x branch

**Comment by thibauthourlier** [comment]
ensembl-pipeline and ensembl-analysis need to be on 1.2.3. Hopefully we will be on 1.6.x when we move to ensembl-annotation

**Pull request merged**
