### PR TITLE
Fixing the test suite and bits of io

### PR DESCRIPTION
**Pull request by andrewyatz**
There's a few changes coming in here. Short summary
- Tests will skip if you don't have Htslib/Kent XS bindings and core API. Tests always run on Travis no matter what
- Expanding the cpanfile and install dependencies
- Rejigged the big file parser
- Removed the VEP_output parser. Will said it wasn't right to keep in
- `Writer.pm` and the `writer.t` test now work. There's some awful delimiter initialisation problem that means I have to _fake open a file_

### CODE REVIEW

**Comment by ens-ap5** [comment]
The VEP_output parser might be 'bogus' as far as variation is concerned, but web needs it in order to display output from the VEP in Region in Detail.

**Comment by andrewyatz** [comment]
Ok I did bring them back in but the test case is failing. This was mentioned in issue #27 that VEP_output.pm or the test suite/file in question just don't seem to agree. Output from the test suite below:

```
ok 1 - Loading first record
ok 2
ok 3
ok 4
ok 5
ok 6
not ok 7
not ok 8
not ok 9
not ok 10
not ok 11

#   Failed test at modules/t/vep_output.t line 31.

#   Failed test at modules/t/vep_output.t line 32.

#   Failed test at modules/t/vep_output.t line 33.

#   Failed test at modules/t/vep_output.t line 34.
Use of uninitialized value in numeric eq (==) at modules/t/vep_output.t line 35, <$__ANONIO__> line 2.

#   Failed test at modules/t/vep_output.t line 35.
Use of uninitialized value in numeric eq (==) at modules/t/vep_output.t line 36, <$__ANONIO__> line 2.
not ok 12

#   Failed test at modules/t/vep_output.t line 36.
Use of uninitialized value in numeric eq (==) at modules/t/vep_output.t line 37, <$__ANONIO__> line 2.
not ok 13

#   Failed test at modules/t/vep_output.t line 37.
Can't locate object method "get_aa_change" via package "Bio::EnsEMBL::IO::Parser::VEP_output" at modules/t/vep_output.t line 38, <$__ANONIO__> line 2.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 25 just after 13.
Dubious, test returned 25 (wstat 6400, 0x1900)
Failed 7/13 subtests

Test Summary Report
-------------------
modules/t/vep_output.t (Wstat: 6400 Tests: 13 Failed: 7)
  Failed tests:  7-13
  Non-zero exit status: 25
  Parse errors: No plan found in TAP output
Files=1, Tests=13,  1 wallclock secs ( 0.02 usr  0.01 sys +  0.02 cusr  0.00 csys =  0.05 CPU)
Result: FAIL
```

**Comment by andrewyatz** [comment]
What is it right to say? Is `VEP_output.pm` correct and the test suite is wrong or is the module wrong?

**Comment by andrewyatz** [comment]
Also just pushed the reverted branch so this test suite will start to fail very very soon

**Comment by ens-ap5** [comment]
I’ll have a look shortly - just in the middle of a bug fix.

Anne

**Comment by ens-ap5** [comment]
Ah, I remember what happened. The VEP interface links to Region in Detail and pulls the results out of the tools database, but I wanted to allow for the fact that someone might download their results as a VEP_output file and then upload them via the user interface at a later date (which I think is not unreasonable to expect). So we do need this parser to cover that scenario, but it looks like it's currently out-of-date.

**Comment by ens-ap5** [comment]
Will fix module - see ticket ENSWEB-2434

**Comment by andrewyatz** [comment]
Okay. From what Will mentioned, and if I have remembered it correctly, the VEP output is dependent on the plugins. So the chances of this output module being of use outside of the webcode is probably low. Best to confirm with him and we can make a decision from there.

**Comment by ens-ap5** [comment]
> On 27 Mar 2016, at 22:03, Andrew Yates <notifications@github.com> wrote:
> 
> Okay. From what Will mentioned, and if I have remembered it correctly, the VEP output is dependent on the plugins. So the chances of this output module being of use outside of the webcode is probably low.

I’m not sure what this means in terms of the file that is produced by the VEP. Presumably the results will be different, because the plugins do filtering and stuff, but we can still display them as a track in Ensembl regardless.

I’ll find out from Will if there are any gotchas regarding the file format, but we should probably ask outreach what users do with their data.

Cheers

Anne


> Best to confirm with him and we can make a decision from there. 
> 
> Sent from my mobile.
>

**Comment by andrewyatz** [comment]
Closing. I think there are bigger problems in the test suite we can solve with the alternative bigwig bindings.

**Pull request closed without merging**
