### PR TITLE
Support parsing from an already open file handle.

### PR DESCRIPTION
**Pull request by andrewyatz**
This changes the code in TextParser to check if the given filename was a file handle. If it is a file handle the code just assigns it and assumes you know what you are doing.

There was also some cleaning up of the open_content() method to delegate to open() once it had created the in-memory filehandle. It seemed odd not to do once open() could support open filehandles.

### CODE REVIEW

**Comment by ens-ap5** [comment]
Seems reasonable - I hacked in the open_content method when I was trying to get the IO parsers to play nicely with the new web upload interface.

**Comment by muffato** [comment]
Do you think TextParser::open() should do a seek() to reset the position to the beginning of the file ? I'm thinking of the scenario where some code opens a file, reads the first bytes to discover which type it is, and then give the file-handle to the relevant ensembl-io parser.

**Comment by andrewyatz** [comment]
Hmmm. I would say no. In the code you’re describing I’d want the code doing that sniffing to reset the file handle position. Otherwise it’s just code second guessing a situation which we may never develop

**Comment by muffato** [comment]
Sounds good to me !

**Comment by andrewyatz** [comment]
That's two :+1: so I'm going to merge

**Pull request merged**
