### PR TITLE
Do not inherit parent html if track has its own html in hubs

### PR DESCRIPTION
**Pull request by brucebolt**
Slight change to the behaviour of my last pull request to fully comply with the spec

### CODE REVIEW

**Comment by andrewyatz** [comment]
Any reason why this hasn't been merged in? @brucebolt have you had any contact with anyone on the io project?

**Comment by brucebolt** [comment]
Doesn't look like it has been merged.  Think I ended up overlooking this pull request as we override this method in the WormBase ParaSite code.

**Comment by ens-ap5** [comment]
I just fixed a bug that we found in Bruce's previous pull request and incorporated the behaviour described in 0a1a277, so I think if I manually reproduce the one-line change in 074eb83 we can discard this pull request altogether.

**Comment by ens-ap5** [comment]
Ha - and I inadvertently replicated 074eb83 last week, because the bug cropped up again.

**Pull request closed without merging**
