### PR TITLE
Attempting to fix the currently breaking test suite.

### PR DESCRIPTION
**Pull request by andrewyatz**
**THIS CANNOT BE MERGED IN YET. DO NOT MERGE**

This branch is a set of changes to master to make sure the test suite runs once again. Already there have been some hidden bugs (seek() in BigWig not `-1` from the given start position) and removal of scripts masquerading as test cases.

There are still some issues with the VEP output code. From what I have seen the input file lacks the following columns

- [ ] consequence
- [ ] impact
- [ ] exon
- [ ] intron
- [ ] hgvsc
- [ ] hgvsp

Are these actually fields in the VEP output or do they come from the final attributes set? Either the input file needs changing or the `VEP_output.pm` parser needs changing.

### CODE REVIEW

**Comment by andrewyatz** [comment]
Leaving a note for @ens-ap5 and @ens-ds23. @ens-ap5 you should check about VEP output. @ens-ds23 I want to make sure there's nothing I've broken here for the web especially changing how seek() operates. Also can you tell me if the test cases for bigBed and bigWig are operating as you expect them to as a client of the code? Thanks

**Comment by ens-ds23** [comment]
Hi Andy,

That's one for @ens-ap5 to answer, really (Anne is back on Monday). I'll 
let you know if it obviously breaks anything, but I know next to nothing 
about ensembl-io or the in-progress rewrite: I'm actually trying to get 
a new regulation track working that just uses it in passing, :-) .

Dan.

**Comment by andrewyatz** [comment]
:+1: I don't think there's many changes I made to the bigbed code that would help out. It was mostly getting the test suites right and code for munging a bit saner.

**Comment by ens-ds23** [comment]
I /think/ the problems earlier were due to using the wrong checkout on 
ensembl-webcode. But the branch I'm using now blows up with memory 
exhaustion. It's all a bit muddy at the moment. Not sure till I fix that 
and actually see data, but I think ensembl-io is off the hook.

Dan.

**Comment by andrewyatz** [comment]
Seems that the issues this was raising have migrated into #33

**Pull request closed without merging**
