### PR TITLE
Update BaseVCF4.pm

### PR DESCRIPTION
**Pull request by magaliruffier**
throw method needs to be imported

### CODE REVIEW

**Comment by magaliruffier** [comment]
probably needs to be fixed on release/80 branch as well, I can submit another pull request for that if you want

**Comment by andrewyatz** [comment]
This could be superseded by PR #16 which keeps core dependencies to a minimum to aid portability into other projects.

**Comment by ens-ap5** [comment]
I haven’t done this merge, since it looked like it wouldn’t be the right thing to do - let me know if/when you need me to do something.

Cheers

Anne

**Comment by andrewyatz** [comment]
I think we can close this issue now. The removal of Ensembl methods from the BaseVCF4Parser make this pull request unnecessary.

**Pull request closed without merging**
